version: '2'

services: 
  samba:
    container_name: samba
    image: dperson/samba
    volumes:
      - /media/hdd/nas:/mount
    ports:
      - "139:139"
      - "445:445"
    restart: always
    command: >
        -s "public;/mount;yes;no;yes"
        -p
    networks:
      net:  
        ipv4_address: 172.26.0.7
networks: 
  net:
    name: traefik-net
    external: true
