version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_data:/config
      - jellyfin_cache:/cache
      - /mnt:/media
    networks:
      traefik_net:
    ports:
      - 8096:8096
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.franz.local`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: always

networks:
  traefik_net:
    name: traefik-net
    external: true

volumes:
  jellyfin_data:
    name: jellyfin_data
  jellyfin_cache:
    name: jellyfin_cache