version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_data:/config
      - jellyfin_cache:/cache
      - /mnt:/media
    networks:
      traefik_net:
    ports:
      - 8096:8096
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.franz.local`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    dns:
      - 1.1.1.1
  vpn:
    image: wiorca/docker-windscribe
    container_name: windscribe
    environment:
      - TZ=Europe/Berlin
      - WINDSCRIBE_PROTOCOL=stealth
      - WINDSCRIBE_PORT=80
      - WINDSCRIBE_LOCATION=NL
      - WINDSCRIBE_LANBYPASS=on
      - WINDSCRIBE_FIREWALL=on
      - PUID=1000
      - PGID=1000
    env_file:
      - windscribe_secrets.env
    volumes:
      - windscribe_data:/config
      - /mnt/Filme:/movies
      - /mnt/Serien:/series
    cap_add:
      - NET_ADMIN
    restart: always
    dns:
      - 1.1.1.1
    networks:
      traefik_net:

  torrent:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - transmission_data:/config
      - /mnt/Downloads:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.routers.transmission.rule=Host(`transmission.franz.local`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.docker.network=traefik-net
    restart: always
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr_data:/config
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
      - torrent
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=web
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.franz.local`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.docker.network=traefik-net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr_data:/config
      - /mnt/Filme:/movies
      - /mnt/Downloads:/downloads
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
      - torrent
      - prowlarr
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`radarr.franz.local`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.docker.network=traefik-net

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - sonarr_data:/config
      - /mnt/Serien:/series
      - /mnt/Downloads:/downloads
    restart: always
    network_mode: service:vpn
    depends_on:
      - vpn
      - torrent
      - prowlarr
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.rule=Host(`sonarr.franz.local`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.docker.network=traefik-net

  bazarr:
    image: hotio/bazarr:latest
    container_name: bazarr
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - bazarr_data:/config
      - /mnt/Filme:/movies
      - /mnt/Serien:/series
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.entrypoints=web
      - traefik.http.routers.bazarr.rule=Host(`bazarr.franz.local`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.docker.network=traefik-net
    networks:
      traefik_net:
    dns:
      - 1.1.1.1

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: always
    volumes:
      - jellyseerr_data:/app/config
    depends_on:
      - vpn
      - torrent
      - prowlarr
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.entrypoints=web
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.franz.local`)
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
      - traefik.docker.network=traefik-net
    networks:
      traefik_net:
    dns:
      - 1.1.1.1


networks:
  traefik_net:
    name: traefik-net
    external: true

volumes:
  jellyfin_data:
    name: jellyfin_data
  windscribe_data:
    name: windscribe_data
  jellyfin_cache:
    name: jellyfin_cache
  transmission_data:
    name: transmission_data
  sonarr_data:
    name: sonarr_data
  prowlarr_data:
    name: prowlarr_data
  radarr_data:
    name: radarr_data
  bazarr_data:
    name: bazarr_data
  jellyseerr_data:
    name: jellyseerr_data