version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "80:80"
    user: uid:gid
    network_mode: "host"
    volumes:
      - jellyfin_data:/config
      - jellyfin_cache:/cache
      - /mnt:/media
    restart: "unless-stopped"


volumes:
  jellyfin_data:
    name: jellyfin_data
    external: true
  jellyfin_cache:
    name: jellyfin_cache
    external: true
