version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - traefik_data:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik_net:
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.franz.local`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.services.dashboard.loadbalancer.server.port=8080
  kuma:
    container_name: kuma
    image: "louislam/uptime-kuma"
    volumes:
      - kuma_data:/app/data
    restart: always
    networks:
      traefik_net:
    dns:
      - 1.1.1.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.entrypoints=web
      - traefik.http.routers.kuma.rule=Host(`kuma.franz.local`)
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - flame_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - flame_secrets.env
    restart: always
    networks:
      traefik_net:
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame.entrypoints=web
      - traefik.http.routers.flame.rule=Host(`franz.local`)
    dns:
      - 1.1.1.1
    profiles:
      - donotstart
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: always
    volumes:
      - homarr_data:/app/data/configs
      - homarr_icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      traefik_net:
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.entrypoints=web
      - traefik.http.routers.homarr.rule=Host(`franz.local`)


networks:
  traefik_net:
    name: traefik-net
    driver: bridge
    external: true
volumes:
  traefik_data:
    name: traefik_data
  kuma_data:
    name: kuma_data
  flame_data:
    name: flame_data
  homarr_data:
    name: homarr_data
  homarr_icons:
    name: homarr_icons