version: "3.5"
services:
  dropbot_m:
    image: ghcr.io/tychothetaco/twitch-drops-bot
    container_name: dropbot_m
    user: 1000:1000
    volumes:
      - dropbot_m_data:/app/data
    restart: "unless-stopped"
  dropbot_p:
    image: ghcr.io/tychothetaco/twitch-drops-bot
    container_name: dropbot_p
    user: 1000:1000
    volumes:
      - dropbot_p_data:/app/data
    restart: "unless-stopped"

volumes:
  dropbot_m_data:
    name: dropbot_m_data
  dropbot_p_data:
    name: dropbot_p_data